In [1]:
import numpy as np

from nems import Model

x = np.random.rand(10000, 18)  # fake spectrogram
m = Model.from_keywords('wc.18x4.g-fir.4x15')
# TODO: shorten model repr? the spaces are nice when there are lots of layers,
#       but it makes short models unnecessary long. And/or could probably add
#       some code to trim whitespace if less than X-many layers.
m  

Model()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.layers:



GaussianWeightChannels(shape=(18, 4))
.parameters:


Parameter(name=mean, shape=(4,))
----------------
.prior:     Normal(μ=array(4), σ=array(4))
.bounds:    (0, 1)
.is_frozen: False
.values:
[0. 0. 0. 0.]
----------------
Index: 0
----------------

Parameter(name=std, shape=(4,))
----------------
.prior:     Normal(μ=array(4), σ=array(4))
.bounds:    (0, inf)
.is_frozen: False
.values:
[0. 0. 0. 0.]
----------------
Index: 0
----------------





FIR(shape=(4, 15))
.parameters:


Parameter(name=coefficients, shape=(4, 15))
----------------
.prior:     Normal(μ=array(4, 15), σ=array(4, 15))
.bounds:    (-inf, inf)
.is_frozen: False
.values:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
----------------
Index: 0
----------------



~~~~~~~~~~~~~~~~~~~~~~~~~~~