In [1]:
import numpy as np

from nems import Model

x = np.random.rand(10000, 18)  # fake spectrogram
# TODO: add Model methods for setting priors to mean, sample, etc
#       (currently every coefficient here defaults to mean of 0).
m = Model.from_keywords('wc.18x4.g-fir.4x15')
# TODO: shorten model repr? the spaces are nice when there are lots of layers,
#       but it makes short models unnecessary long. And/or could probably add
#       some code to trim whitespace if less than X-many layers.
m  

Model()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.layers:



GaussianWeightChannels(shape=(18, 4))
.parameters:


Parameter(name=mean, shape=(4,))
----------------
.prior:     Normal(μ=array(4), σ=array(4))
.bounds:    (0, 1)
.is_frozen: False
.values:
[0. 0. 0. 0.]
----------------
Index: 0
----------------

Parameter(name=std, shape=(4,))
----------------
.prior:     Normal(μ=array(4), σ=array(4))
.bounds:    (0, inf)
.is_frozen: False
.values:
[0. 0. 0. 0.]
----------------
Index: 0
----------------





FIR(shape=(4, 15))
.parameters:


Parameter(name=coefficients, shape=(4, 15))
----------------
.prior:     Normal(μ=array(4, 15), σ=array(4, 15))
.bounds:    (-inf, inf)
.is_frozen: False
.values:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
----------------
Index: 0
----------------



~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [12]:
wc = m.layers[0]
fir = m.layers[1]
# TODO: have wc, fir not return list if only one?
#       wastes operations in Model.evaluate but would
#       make testing of individual layers more intuitive
y = wc.evaluate(x)[0]
z1 = fir.evaluate(y)[0]
z2 = fir.old_evaluate(y)[0]
np.sum(np.isnan(z1)) + np.sum(np.isnan(z2))  # nans always !=

c:\code\nems-lite\nems\layers\weight_channels.py:180: RuntimeWarning: divide by zero encountered in true_divide
  coefficients = np.exp(-0.5*((x-mean)/std)**2).T
c:\code\nems-lite\nems\layers\weight_channels.py:180: RuntimeWarning: invalid value encountered in true_divide
  coefficients = np.exp(-0.5*((x-mean)/std)**2).T


20000

In [13]:
np.sum(z1 != z2)

10000