In [1]:
import numpy as np
from nems import Model

stim = np.ones(shape=(10000,18))
state = np.ones(shape=(10000,2)) + 1
input = {'stim': stim, 'state': state}

m = Model.from_keywords('wc.18x4.g-stategain.2x4-fir.4x15')
m['stategain']

StateGain(shape=(2, 4))
.parameters:

Parameter(name=gain, shape=(2, 4))
----------------
.prior:     Normal(μ=array(2, 4), σ=array(2, 4))
.bounds:    (-inf, inf)
.is_frozen: False
.values:
[[1. 1. 1. 1.]
 [0. 0. 0. 0.]]
----------------
Index: 0
----------------

Parameter(name=offset, shape=(2, 4))
----------------
.prior:     Normal(μ=array(2, 4), σ=array(2, 4))
.bounds:    (-inf, inf)
.is_frozen: False
.values:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------------
Index: 0
----------------


In [2]:
data = m.evaluate(input, input_name='stim', state_name='state')
data['output'].shape

(10000, 1)

In [ ]:
# TODO: pick some toy stimulus/state inputs and parameter values that would be
#       better for testing (i.e. to make sure that weighted channels are being
#       applied in the appropriate places).

In [5]:
# In this case, the single weighted state channel should be broadcast to all
# stim channels.
state2 = np.ones(shape=(10000,2)) + 1
input2 = {'stim': stim, 'state': state2}
m2 = Model.from_keywords('wc.18x4.g-stategain.2x1-fir.4x15')
data2 = m2.evaluate(input2, input_name='stim', state_name='state')
data2['output'].shape

(10000, 1)