In [1]:
import numpy as np

from nems import Model
from nems.layers import NumPy

x = np.arange(12).reshape(3, 4)
y = np.split(x, 3, axis=0)
split = NumPy('split', 3, axis=0)
z = split.evaluate(x)

In [2]:
y

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [3]:
z

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [4]:
# This should be the same as the first split
split2 = NumPy.from_keyword('np.split.3.axis0')
split2.evaluate(x)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [5]:
y2 = np.vstack(y)
vstack = NumPy('vstack')
z2 = vstack.evaluate(z)

In [6]:
y2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
z2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
# This should do the same thing
concat = NumPy('concatenate', axis=0)
concat.evaluate(y)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a = np.arange(10)
b = np.sum(a)
model = Model.from_keywords('np.sum')
c = model['np.sum'].evaluate(a)
b == c

True

In [10]:
d = np.ones(shape=(4,3))
e = np.ones(shape=(3,5))*2
f = np.matmul(d,e)
model2 = Model.from_keywords('np.matmul')
g = model2['np.matmul'].evaluate(d, e)
np.all(f == g)

True

In [11]:
g.shape

(4, 5)

In [12]:

h = np.transpose(g, axes=[1,0])
model3 = Model.from_keywords('np.transpose.axes[1,0]')
i = model3['np.transpose'].evaluate(g)
np.all(h == i)

True

In [13]:
i.shape

(5, 4)

In [14]:
# Methods below should return blank/null/default values, but should not
# raise an Exception.
model.get_bounds_vector()

[]

In [15]:
model.priors

{'np.sum': {}}

In [16]:
model.bounds

{'np.sum': {}}

In [17]:
model.get_parameter_values()

{'np.sum': {}}

In [18]:
model.get_parameter_vector()

[]

In [19]:
model.layers

{'np.sum': NumPy(shape=None)
}

In [20]:
model['np.sum'].parameters.__repr__()

''

In [21]:
print(model['np.sum'].parameters)